#!/bin/bash
# install.sh — Firefox Hardening Installer
# Run INSIDE the Alpine VM as root after Firefox is installed.
# Generated by generate-firefox-config.sh — do not edit manually.

set -e

FIREFOX_BIN="/usr/bin/firefox"
FIREFOX_LIB="/usr/lib/firefox"
POLICY_DIR="$FIREFOX_LIB/distribution"
PREF_DIR="$FIREFOX_LIB/defaults/pref"
EXTENSION_DEST="/opt/kiosk-guard"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "══════════════════════════════════════════════"
echo " Firefox Hardening Installer"
echo "══════════════════════════════════════════════"
echo ""

[ "$EUID" -ne 0 ]          && echo "✖  Run as root." && exit 1
[ ! -f "$FIREFOX_BIN" ]    && echo "✖  Firefox not found. Run: apk add firefox" && exit 1
command -v zip &>/dev/null || apk add --no-cache zip

echo "✔  Firefox found: $FIREFOX_BIN"
echo ""

echo "[1/4] Installing policies.json..."
mkdir -p "$POLICY_DIR"
cp "$SCRIPT_DIR/config/policies.json" "$POLICY_DIR/policies.json"
chmod 644 "$POLICY_DIR/policies.json"

echo "[2/4] Installing autoconfig.js + firefox.cfg..."
mkdir -p "$PREF_DIR"
cp "$SCRIPT_DIR/config/autoconfig.js" "$PREF_DIR/autoconfig.js"
cp "$SCRIPT_DIR/config/firefox.cfg"   "$FIREFOX_LIB/firefox.cfg"
chmod 644 "$PREF_DIR/autoconfig.js" "$FIREFOX_LIB/firefox.cfg"

echo "[3/4] Packaging kiosk-guard extension..."
mkdir -p "$EXTENSION_DEST"
cd "$SCRIPT_DIR/extension"
zip -r "$EXTENSION_DEST/kiosk-guard.xpi" manifest.json background.js content.js
chmod 644 "$EXTENSION_DEST/kiosk-guard.xpi"
cd "$SCRIPT_DIR"

echo "[4/4] Creating Downloads folder..."
mkdir -p /home/browser/Downloads
chown browser:browser /home/browser/Downloads 2>/dev/null || true
chmod 750 /home/browser/Downloads

echo ""
echo "══════════════════════════════════════════════"
echo " Installation complete. Reboot the VM."
echo "══════════════════════════════════════════════"
