"use strict";
// KIOSK GUARD — background.js
// Generated by generate-firefox-config.sh
// Preseed profile: Standard Secure Browsing  (balanced settings)

// ═══════════════════════════════════════════════════════════════════════
// CONFIGURATION — values driven from preseed.conf
// ═══════════════════════════════════════════════════════════════════════

// PRESEED: ALLOW_DOWNLOADS=yes
const DOWNLOADS_ENABLED = true;

// PRESEED: MAX_FILE_SIZE_MB=512
const MAX_DOWNLOAD_SIZE_MB    = 512;
const MAX_DOWNLOAD_SIZE_BYTES = MAX_DOWNLOAD_SIZE_MB * 1024 * 1024;

// File type categories — driven from preseed ALLOW_* flags
// PRESEED: ALLOW_DOCS=yes  ALLOW_IMGS=yes  ALLOW_ARCH=yes  ALLOW_EXEC=no
const ALLOW_DOCS = true;   // .pdf .doc .docx .xls .xlsx .ppt .pptx .odt .ods .txt .csv .rtf
const ALLOW_IMGS = true;   // .jpg .jpeg .png .gif .webp .bmp .svg .tiff .ico .avif
const ALLOW_ARCH = true;   // .zip .tar .gz .bz2 .xz .7z .rar .zst
const ALLOW_EXEC = false;   // .exe .msi .bat .cmd .sh .run .AppImage .deb .rpm .apk .bin .ps1 .vbs

// Extension → category map (longest-match first at runtime)
const FILE_TYPE_CATEGORIES = {
  ".pdf":"docs",  ".doc":"docs",  ".docx":"docs", ".xls":"docs",
  ".xlsx":"docs", ".ppt":"docs",  ".pptx":"docs", ".odt":"docs",
  ".ods":"docs",  ".odp":"docs",  ".txt":"docs",  ".csv":"docs",  ".rtf":"docs",
  ".jpg":"imgs",  ".jpeg":"imgs", ".png":"imgs",  ".gif":"imgs",
  ".webp":"imgs", ".bmp":"imgs",  ".svg":"imgs",  ".tiff":"imgs",
  ".ico":"imgs",  ".avif":"imgs",
  ".zip":"arch",  ".tar":"arch",  ".gz":"arch",   ".bz2":"arch",
  ".xz":"arch",   ".7z":"arch",   ".rar":"arch",  ".zst":"arch",
  ".exe":"exec",  ".msi":"exec",  ".bat":"exec",  ".cmd":"exec",
  ".sh":"exec",   ".run":"exec",  ".appimage":"exec", ".deb":"exec",
  ".rpm":"exec",  ".apk":"exec",  ".bin":"exec",  ".com":"exec",
  ".ps1":"exec",  ".vbs":"exec",
};

const CATEGORY_ALLOWED = {
  docs: ALLOW_DOCS,
  imgs: ALLOW_IMGS,
  arch: ALLOW_ARCH,
  exec: ALLOW_EXEC,
};

// PRESEED: LOG_URLS=yes  LOG_DOWNLOADS=yes
const LOG_TO_STORAGE      = true;
const MAX_URL_LOG_ENTRIES = 10000;
const MAX_EVT_LOG_ENTRIES = 5000;

// Host log endpoint — POST target for real-time log entries
const LOG_ENDPOINT = "http://127.0.0.1:8888/log";


// ═══════════════════════════════════════════════════════════════════════
// URL Capture
// ═══════════════════════════════════════════════════════════════════════

function captureURL(tabId, url, event) {
  if (!url)                             return;
  if (url.startsWith("about:"))         return;
  if (url.startsWith("moz-extension:")) return;
  if (url.startsWith("chrome:"))        return;
  if (url === "")                       return;

  const entry = {
    timestamp : new Date().toISOString(),
    type      : "url_visit",
    event,
    tabId,
    url,
  };
  storeEntry("urlLog", entry, MAX_URL_LOG_ENTRIES);
  sendToHost(entry);
}

browser.tabs.onCreated.addListener((tab) => {
  if (tab.url) captureURL(tab.id, tab.url, "tab_created");
});

browser.tabs.onUpdated.addListener((tabId, changeInfo) => {
  if (changeInfo.url) captureURL(tabId, changeInfo.url, "tab_updated");
});

browser.tabs.onActivated.addListener(({ tabId }) => {
  browser.tabs.get(tabId)
    .then((tab) => { if (tab.url) captureURL(tab.id, tab.url, "tab_activated"); })
    .catch(() => {});
});


// ═══════════════════════════════════════════════════════════════════════
// Download Control
// Check order: (1) global toggle → (2) file type → (3) size limit
// ═══════════════════════════════════════════════════════════════════════

browser.downloads.onCreated.addListener((item) => {

  // Check 1: Global toggle
  if (!DOWNLOADS_ENABLED) {
    cancelDownload(item.id);
    logEvent("download_blocked_toggle", {
      url: item.url, filename: item.filename,
      reason: "Downloads are disabled by policy.",
    });
    return;
  }

  // Check 2: File type filter
  const typeBlock = getFileTypeBlock(item.filename || item.url);
  if (typeBlock) {
    cancelDownload(item.id);
    logEvent("download_blocked_filetype", {
      url: item.url, filename: item.filename,
      category: typeBlock.category, reason: typeBlock.reason,
    });
    return;
  }

  // Check 3: Size limit (skip when totalBytes unknown)
  if (item.totalBytes > 0 && item.totalBytes > MAX_DOWNLOAD_SIZE_BYTES) {
    cancelDownload(item.id);
    const actualMB = (item.totalBytes / (1024 * 1024)).toFixed(1);
    logEvent("download_blocked_size", {
      url: item.url, filename: item.filename,
      actualMB, limitMB: MAX_DOWNLOAD_SIZE_MB,
      reason: `File is ${actualMB} MB — exceeds the ${MAX_DOWNLOAD_SIZE_MB} MB limit.`,
    });
    return;
  }

  // All checks passed
  logEvent("download_allowed", {
    url: item.url, filename: item.filename,
    sizeMB: item.totalBytes > 0 ? (item.totalBytes / (1024 * 1024)).toFixed(1) : "unknown",
  });
});

// Returns { category, reason } if the file should be blocked, else null.
function getFileTypeBlock(nameOrUrl) {
  let name = nameOrUrl || "";
  try {
    const u = new URL(nameOrUrl);
    name = u.pathname.split("/").pop() || nameOrUrl;
  } catch (_) {}
  name = name.toLowerCase().split("?")[0];

  const exts = Object.keys(FILE_TYPE_CATEGORIES).sort((a, b) => b.length - a.length);
  for (const ext of exts) {
    if (name.endsWith(ext)) {
      const category = FILE_TYPE_CATEGORIES[ext];
      if (CATEGORY_ALLOWED[category] === false) {
        return { category, reason: `File type "${ext}" (category: ${category}) is blocked by policy.` };
      }
      return null;
    }
  }
  return null; // unknown extension — let host AV handle it
}

// ─── Helpers ────────────────────────────────────────────────────────────

function cancelDownload(id) {
  browser.downloads.cancel(id)
    .then(() => browser.downloads.erase({ id }))
    .catch(() => {});
}

function storeEntry(key, entry, maxEntries) {
  if (!LOG_TO_STORAGE) return;
  browser.storage.local.get(key).then((result) => {
    const log = result[key] || [];
    log.push(entry);
    if (log.length > maxEntries) log.splice(0, log.length - maxEntries);
    browser.storage.local.set({ [key]: log });
  }).catch(() => {});
}

function logEvent(type, data) {
  const entry = { timestamp: new Date().toISOString(), type, ...data };
  storeEntry("eventLog", entry, MAX_EVT_LOG_ENTRIES);
  sendToHost(entry);
}

function sendToHost(entry) {
  fetch(LOG_ENDPOINT, {
    method : "POST",
    headers: { "Content-Type": "application/json" },
    body   : JSON.stringify(entry),
  }).catch(() => {});
}
