"use strict";
// KIOSK GUARD — content.js
// Generated by generate-firefox-config.sh
// Preseed profile: Standard Secure Browsing  (balanced settings)
//
// Runs at document_start on every page and frame.
// Intercepts keyboard events before any page script sees them.


// ── Configuration (from preseed) ──────────────────────────────────────
// PRESEED: KIOSK_MODE=no
// When KIOSK_MODE=yes: all Ctrl combos blocked, Escape blocked.
// When KIOSK_MODE=no:  copy/cut/paste/select-all pass through.

// Ctrl combos that are allowed to pass through (ignored when BLOCK_ALL_CTRL=true)
const ALLOWED_CTRL_KEYS = ["a","c","v","x"];

// true = block ALL Ctrl combos including copy/paste (kiosk mode)
// false = allow the keys listed in ALLOWED_CTRL_KEYS
const BLOCK_ALL_CTRL = false;

// Function keys to block (F5 refresh, F11 fullscreen, F12 devtools, etc.)
const BLOCKED_FUNCTION_KEYS = [
  "F1","F2","F3","F4","F5","F6",
  "F7","F8","F9","F10","F11","F12"
];

// PRESEED: KIOSK_MODE=no
// true = Escape blocked (user cannot dismiss dialogs or exit fullscreen)
const BLOCK_ESCAPE = false;


// ── Event Interception ────────────────────────────────────────────────
window.addEventListener("keydown", handleKey, true);
window.addEventListener("keyup",   handleKey, true);

function handleKey(event) {
  const ctrl  = event.ctrlKey || event.metaKey;
  const alt   = event.altKey;
  const key   = event.key;
  const keyLo = key.toLowerCase();

  // Block ALL Alt combinations (Alt+F4, Alt+Left/Right, Alt+D, Alt+Home…)
  if (alt) {
    suppress(event);
    return;
  }

  // Ctrl / Cmd combinations
  if (ctrl) {
    if (BLOCK_ALL_CTRL) {
      suppress(event);
      return;
    }
    if (!ALLOWED_CTRL_KEYS.includes(keyLo)) {
      suppress(event);
      return;
    }
    return; // allowed combo — pass through
  }

  // Function keys
  if (BLOCKED_FUNCTION_KEYS.includes(key)) {
    suppress(event);
    return;
  }

  // Escape
  if (BLOCK_ESCAPE && key === "Escape") {
    suppress(event);
    return;
  }
}

function suppress(event) {
  event.preventDefault();
  event.stopPropagation();
  event.stopImmediatePropagation();
}

// NOTE: Browser-chrome shortcuts (Ctrl+T, Ctrl+W, Ctrl+L, Ctrl+Tab) are
// handled by Firefox itself and are NOT reachable from a content script.
// Those are covered by:
//   • policies.json → BlockAboutConfig (blocks Ctrl+L → about:config)
//   • Firefox --kiosk flag (if KIOSK_MODE=yes) → disables Ctrl+W, Ctrl+N, Ctrl+Q
//   • policies.json → DisableDeveloperTools → blocks Ctrl+Shift+I / F12
